# app/services/reporting.py
import io
import re
import logging
from xhtml2pdf import pisa
from datetime import datetime
from typing import Dict, Any


def build_report_html(ai_text: str, stats: Dict[str, Any], trend_b64: str, sev_b64: str) -> str:
    # Convert Markdown to HTML
    body = ai_text.replace("\n", "<br/>")
    body = re.sub(r'### (.*?)(<br/>|$)', r'<h3>\1</h3>', body)
    body = re.sub(r'## (.*?)(<br/>|$)', r'<h2>\1</h2>', body)
    body = re.sub(r'# (.*?)(<br/>|$)', r'<h1>\1</h1>', body)
    body = re.sub(r'\*\*(.*?)\*\*', r'<strong>\1</strong>', body)

    return f"""
    <html>
    <head>
        <style>
            @page {{ size: a4; margin: 1.5cm; }}
            body {{ font-family: Helvetica, sans-serif; color: #333; line-height: 1.5; font-size: 10pt; }}
            h1 {{ color: #1a202c; border-bottom: 2px solid #2d3748; padding-bottom: 5px; }}
            h2 {{ color: #2d3748; margin-top: 25px; border-bottom: 1px solid #e2e8f0; }}
            h3 {{ color: #3182ce; background: #f7fafc; padding: 5px; margin-top: 15px; border-left: 4px solid #3182ce; }}
            .stats-table {{ width: 100%; border-collapse: collapse; margin: 20px 0; }}
            .stats-table td {{ padding: 8px; border: 1px solid #edf2f7; }}
            .stats-table .label {{ font-weight: bold; background: #f8fafc; width: 40%; }}
            .chart {{ width: 100%; max-height: 250px; margin-top: 15px; border: 1px solid #f0f0f0; }}
            .footer {{ text-align: center; font-size: 8pt; color: #a0aec0; margin-top: 40px; }}
        </style>
    </head>
    <body>
        <h1>Security Intelligence Report</h1>
        <p><strong>Date:</strong> {datetime.now().strftime('%Y-%m-%d %H:%M:%S UTC')}</p>
        
        <table class="stats-table">
            <tr><td class="label">Total Threats Detected</td><td>{stats.get('total_threat_events', 0)}</td></tr>
            <tr><td class="label">Active Blocks</td><td>{stats.get('rate_limited_ip_count', 0)}</td></tr>
        </table>

        {body}

        <pdf:nextpage />
        <h2>Visual Analytics</h2>
        <h3>Threat Velocity</h3>
        <img src="{trend_b64}" class="chart" />
        
        <h3>Severity Distribution</h3>
        <img src="{sev_b64}" class="chart" style="width: 70%;" />

        <div class="footer">Confidential | Generated by AI Security Agent</div>
    </body>
    </html>
    """


def create_pdf_report(ai_text, stats, trend_b64, sev_b64) -> bytes:
    result = io.BytesIO()
    html = build_report_html(ai_text, stats, trend_b64, sev_b64)
    pisa.CreatePDF(html, dest=result, encoding='utf-8')
    return result.getvalue()
